# Generated by Django 6.0 on 2026-01-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('short_description', models.CharField(max_length=300, verbose_name='সংক্ষিপ্ত বিবরণ')),
                ('description', models.TextField(verbose_name='বিস্তারিত বিবরণ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='ছবি')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
