# Generated by Django 6.0 on 2026-01-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='লেখকের নাম')),
                ('position', models.CharField(max_length=100, verbose_name='পদবী/পদ')),
                ('message', models.TextField(verbose_name='বার্তা/বক্তব্য')),
                ('image', models.ImageField(blank=True, null=True, upload_to='our_work/', verbose_name='লেখকের ছবি')),
                ('is_active', models.BooleanField(default=True, verbose_name='প্রকাশিত')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Our Work',
                'verbose_name_plural': 'Our Works',
                'ordering': ['-created_at'],
            },
        ),
    ]
