# Generated by Django 6.0.1 on 2026-01-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='প্রকল্পের নাম')),
                ('short_description', models.CharField(max_length=300, verbose_name='সংক্ষিপ্ত বিবরণ')),
                ('description', models.TextField(verbose_name='বিস্তারিত বিবরণ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='প্রকল্পের ছবি')),
                ('video', models.FileField(blank=True, null=True, upload_to='projects/videos/', verbose_name='প্রকল্পের ভিডিও')),
                ('status', models.CharField(choices=[('ongoing', 'চলমান'), ('completed', 'সম্পন্ন'), ('upcoming', 'আসন্ন')], default='ongoing', max_length=20, verbose_name='প্রকল্পের অবস্থা')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='শুরুর তারিখ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='শেষ তারিখ')),
                ('is_active', models.BooleanField(default=True, verbose_name='প্রকাশিত')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
