# Generated by Django 6.0 on 2026-01-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('short_description', models.CharField(max_length=300, verbose_name='সংক্ষিপ্ত বিবরণ')),
                ('media_type', models.CharField(choices=[('image', 'ছবি'), ('video', 'ভিডিও'), ('news', 'সংবাদ')], max_length=20, verbose_name='মিডিয়ার ধরন')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='ছবি')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='ভিডিও লিংক (YouTube/Facebook)')),
                ('is_active', models.BooleanField(default=True, verbose_name='প্রকাশিত')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['-created_at'],
            },
        ),
    ]
