# Generated by Django 6.0 on 2026-01-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='ভিডিও লিংক (YouTube/Facebook/Instagram)'),
        ),
    ]
