# Generated by Django 6.0 on 2026-01-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ইভেন্টের নাম')),
                ('short_description', models.CharField(max_length=300, verbose_name='সংক্ষিপ্ত বিবরণ')),
                ('description', models.TextField(verbose_name='বিস্তারিত বিবরণ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='ইভেন্টের ছবি')),
                ('event_type', models.CharField(choices=[('seminar', 'সেমিনার'), ('workshop', 'ওয়ার্কশপ'), ('training', 'প্রশিক্ষণ'), ('conference', 'কনফারেন্স'), ('other', 'অন্যান্য')], default='other', max_length=20, verbose_name='ইভেন্টের ধরন')),
                ('event_date', models.DateField(verbose_name='ইভেন্টের তারিখ')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='ইভেন্টের সময়')),
                ('location', models.CharField(max_length=200, verbose_name='স্থান')),
                ('is_active', models.BooleanField(default=True, verbose_name='প্রকাশিত')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date'],
            },
        ),
    ]
