# Generated by Django 6.0.1 on 2026-01-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='নাম')),
                ('email', models.EmailField(max_length=254, verbose_name='ইমেইল')),
                ('subject', models.CharField(max_length=200, verbose_name='বিষয়')),
                ('message', models.TextField(verbose_name='বার্তা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='পঠিত হয়েছে')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
