# Generated by Django 6.0 on 2026-01-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('author', models.CharField(max_length=150, verbose_name='লেখক/প্রকাশক')),
                ('description', models.TextField(verbose_name='সংক্ষিপ্ত বিবরণ')),
                ('file', models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='ফাইল (PDF, DOC, ইত্যাদি)')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='প্রকাশের তারিখ')),
                ('is_active', models.BooleanField(default=True, verbose_name='প্রকাশিত')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
    ]
